[tool.poetry]
name = "cw-4"
version = "0.1.0"
description = ""
authors = ["ptichka-tanya <t.n.sinitsina@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
